### ISSUE TITLE
Figure out what UI component library to use or whether to build our own

### ISSUE THREAD

**Issue by aaronsn** [SatcherInstitute/het-frontend#10]
This depends on UX deciding on a design system. Looks like UX is leaning towards material.

Some popular options for libraries include:
- material: https://www.npmjs.com/package/@material-ui/core
- ant: https://www.npmjs.com/package/antd

I'm sure there are many more but these are both widely used/supported/documented.

Alternatively we could create our own component library, which would allow much more granular control and customizability, but at the cost of extra time to develop and maintain it. Chris suggested that if we do this, use https://storybook.js.org/ to manage/document the library.

My instinct is to use an existing design system and use a popular library that implements it to save ourselves the additional work. Note that if we do use an existing component library we should make sure it supports the customizations we need.

**Comment by aaronsn** [comment]
UX has confirmed we're using material design. I had a good experience using the material-ui library which provides a lot of out-of-the-box components and is popular/well-supported. It also lets you customize theme and even swap out individual components internally, so I think it should be flexible enough. Given that, I'd rather use that instead of building our own library which will take longer and may be overkill for what we need.

Krista - lmk what you think about this and if you have any concerns/other things to consider

Also worth noting that if necessary we can always revisit this decision down the road if/when we encounter different needs that might warrant a different solution.

**Comment by kkatzen** [comment]
Sounds great :D 
I'll close this issue.
