### ISSUE TITLE
Set up CSS to consistently style components

### ISSUE THREAD

**Issue by aaronsn** [SatcherInstitute/het-frontend#11]
This sort of depends on whether we continue using the material-ui library. For now I just used the material-ui CssBaseline component which gives some reasonable defaults. If we continue using the library we'll probably want to customize the theme. If not we'll need to do more of our own styling across various components.

Also, Chris initially suggested setting font-size to 62.5% so we can use rems for font-size elsewhere and 1rem == 10px, etc. I reset this to 100% because it was overriding the font-size in the material-ui library. Going to postpone this decision until we know whether we're even going to stick with that library (https://github.com/SatcherInstitute/het-frontend/issues/10). After that we can look more into whether we can do the 62.5% strategy and not break the material-ui library, or if we want to drop that piece.

**Comment by kkatzen** [comment]
Closing this since we have MaterialTheme now...
