### ISSUE TITLE
Finalize web server hosting decision and document tradeoffs

### ISSUE THREAD

**Issue by aaronsn** [SatcherInstitute/het-frontend#20]
Right now we're using a netlify setup, which has a lot of conveniences like automatic previews from github, but is much less flexible. For features that require more server support like an admin login, we'd need to switch to a Node.js or Flask server (or other, but those are the two natural choices so we don't have to fragment our codebase into three languages).

With a Node.js or Flask server, you don't get as much out of the box like with Netlify, but they have other flexibility benefits like being able to implement features that require server-side support and hosting in GCP (which means it can be managed the same as other resources, we can control backend API access, etc).

Some other considerations with Netlify:
- Requires a paid account for more than one login. This would very likely be a requirement for the main website as we'd want developers to be able to access it
- The marketing/informational website is on Netlify. It may be convenient to have both of them there. Is this website going to stick around long-term or be turned into a landing page for the main website?
- Does netlify scale with production apps?

We should definitely sort this out but I'd recommend punting the decision until we've built more of the frontend and data server.

**Comment by aaronsn** [comment]
Quick note on this - Krista has been having issues accessing netlify-hosted domains. If we're gonna use netlify we should figure out why this is happening.

@kkatzen

**Comment by kkatzen** [comment]
I'll claim issue for now just to track that I need to resolve why I can't use Netlify as that may factor into the decision

**Comment by aaronsn** [comment]
Per offline discussion, I'm gonna take a look into this and try to get a better understanding of the tradeoffs here.

**Comment by aaronsn** [comment]
Closing this out, as we've decide on an approach. Will file issues for implementation of that approach
