### ISSUE TITLE
Consider using state management to handle global state or a data fetching library to simplify global state

### ISSUE THREAD

**Issue by kkatzen** [SatcherInstitute/het-frontend#6]

**Comment by aaronsn** [comment]
From offline discussion - let's wait to set this up for now until we make more progress on the actual features and see how our needs evolve. We may not even need Redux, and if we do then it's valuable to go into it with a clear picture of what we need it for.

**Comment by aaronsn** [comment]
Wrote up summary of options here: https://docs.google.com/document/d/1QgVbPAppfD4IjbovgeZo1gKjmv-GX_5OUpPiMwtV13w/edit. Currently we have a working implementation of dataset loading using vanilla React, so no need to go down this path yet.

**Comment by aaronsn** [comment]
Closing this out, I think we have a working system that doesn't require a state management system
